dbt_spark_project:
  outputs:
    dev:
      host: localhost
      method: thrift
      port: 10000
      schema: default
      threads: 1
      type: spark
  target: dev
my_dbt_project:
  outputs:
    dev:
      dbname: postgres
      host: localhost
      password: disconme123
      port: 5432
      schema: public
      threads: 4
      type: postgres
      user: dbt_user
  target: dev
my_second_dbt_project:
  outputs:
    dev:
      path: dev.duckdb
      threads: 1
      type: duckdb
    prod:
      path: prod.duckdb
      threads: 4
      type: duckdb
  target: dev
